### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by m21camby** [SchubertLab/mvTCR#10]
Dear the author, 

I'm having below error while install mvtcr `pip install mvtcr` in my conda environment. 

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> scikit-misc 0.2.0 requires numpy>=1.22.3, but you have numpy 1.20.3 which is incompatible.

Let me know how to fix this issue. 
Thank you

**Comment by leuschjanphilipp** [comment]
Hi,
thanks for the interest in mvTCR!

The current `pip install mvtcr` should be installed in a fresh environment with the following command:
`conda create --name mvTCR python=3.8.8 -y && conda activate mvTCR && pip install mvtcr && conda install nb_conda_kernels -y`. 
If you want to use mvTCR with GPU support, please (re)install [torch](https://pytorch.org/get-started/locally/) afterwards since cuda / rocm / mps is not installed.

The dependency errors occurs, because the current mvtcr version (pypi mvtcr 0.1.2) installs the environment used in the [publication](https://www.biorxiv.org/content/10.1101/2021.06.24.449733v2), which uses older versions of e.g. numpy or optuna, which are incompatible with newer versions of in this case scikit.

We are currently testing a new version and there will be an update soon, so stay tuned!

If there are still issues, please post them here so we can work on a fix.
Cheers
