### ISSUE TITLE
ImportError: cannot import name 'init_model' from 'tcr_embedding.utils_training' 

### ISSUE THREAD

**Issue by xpgege** [SchubertLab/mvTCR#2]
In the 10x_optuna_tutorial.pynb

from tcr_embedding.utils_training import init_model

however, there is not a function named "init_model" in the "tcr_embedding/utils_training.py" file

**Comment by drEast** [comment]
Thanks for your interest.
Due to a major formating of the code base, the tutorials from the earlier version do no longer work. I will update them accordingly in the next weeks. 
In the meantime you can find a similar experiment as described in the notebook in the files: 

experiments/10x_optuna.py 
experiments/10x_full_optuna.py

Sorry for the inconvenience. I will close this issue, when I have updated the tutorials.

**Comment by drEast** [comment]
The tutorial folder now contains notebooks for:
- preprocessing
- training your models for data analysis
- training your models for specificity prediction.

Best,
Felix
