### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by jiangdada1221** [SchubertLab/mvTCR#4]
Hi,

It seems that there is no 'experiments/10x_evaluate_models.ipynb' in the repository. 

I download the donor1 file from 10x genomics from 'https://www.10xgenomics.com/resources/datasets/cd-8-plus-t-cells-of-healthy-donor-1-1-standard-3-0-2'. Specifically, I downloaded the 'binarized matrix CSV'.

However, I found it records ~40000 items and after deleting those that have no 'TRB' sequence, there are only ~13000 items left. Then, I filter out the duplicates and at last I have only ~3600 items left. So, it seems to contradict to Figure 2 in the paper as I think there are more than 3600 points in this plot. (Besides, 'KLGGALQAK'-specific TCRs take up 50% of the data (~1800items), which clearly contradicts to figure 2)

Could you resolve my question?

**Comment by drEast** [comment]
Hi,
Thanks for your interest.
We moved all preprocessing, experiments files, evaluation, and figure code to a reproducibility repo (https://github.com/SchubertLab/mvTCR_reproducibility), so that the mvTCR repo only contains the code of the tool. I forgot to update the README. Thanks for letting us know about this mistake.

Concerning data sizes: 
The reproducibility repo also contains notebooks on how we preprocessed this data. I also ran a quick test on the 'binarized matrix CSV' , where I obtained different results. Can you please provide me the code of your filtering steps? 

In the quick test, I used the following: 
```
# read the data => 46,526 cells
df_binding = pd.read_csv('data/vdj_v1_hs_aggregated_donor1_binarized_matrix.csv')
# filtering for cells with TRB => 45,192 cells
df_binding = df_binding[df_binding['cell_clono_cdr3_aa'].str.contains('TRB')]
# filtering for cells with TRA => 39,822 cells
df_binding = df_binding[df_binding['cell_clono_cdr3_aa'].str.contains('TRA')]
```
Note, that this is not the code used in the paper (for simplicity reasons) since we apply further single-cell preprocessing steps. However, the amount with TRB heavily exceeds the number you stated. Can you please check / post this filtering step?

Thanks and best,
Felix
